<a href="https://colab.research.google.com/github/ShriVarshaan/pytorch-learning-log/blob/main/pytorch_funamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00 Pytorch fundamentals

Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
!pip install torch

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
print(torch.__version__)

2.6.0+cu124


Creating a scalar tensor

created using torch.tensor



In [8]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim
# the scalar has no dimensions, ndim gives us the numer of dimensions, also called the rank

0

In [10]:
# getting tensor back as Python int
scalar.item()

7

In [14]:
#Vectors

vector = torch.tensor([7,7, 8])
vector

tensor([7, 7, 8])

In [16]:
vector.ndim
#Think of the number of dimensions as the number of square bracket pairs

1

In [20]:
vector.shape

torch.Size([3])

In [21]:
#matrix

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [22]:
MATRIX.ndim

2

In [23]:
MATRIX[0]

tensor([7, 8])

In [24]:
MATRIX.shape

torch.Size([2, 2])

In [26]:
#tensor

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 6]]])

In [29]:
TENSOR.ndim

3

In [30]:
TENSOR.shape

torch.Size([1, 3, 3])

Scalars and vectors are denoted with lowercase letters while tensors and matrices are denoted using uppercase letters.

Scalar has 0 dimensions
Vector has 1 dimension
Matrix has 2

tensor can be any number of dimensions, 0 dimension tensor is a scalar, 2 is a vector......

In [31]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 6]])

In [33]:
TENSOR[0][1]

tensor([3, 6, 9])