<a href="https://colab.research.google.com/github/ShriVarshaan/pytorch-learning-log/blob/main/pytorch_funamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###00 Pytorch fundamentals

Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
!pip install torch

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.6.0+cu124


Creating a scalar tensor

created using torch.tensor



In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim
# the scalar has no dimensions, ndim gives us the numer of dimensions, also called the rank

0

In [ ]:
# getting tensor back as Python int
scalar.item()

7

In [ ]:
#Vectors

vector = torch.tensor([7,7, 8])
vector

tensor([7, 7, 8])

In [ ]:
vector.ndim
#Think of the number of dimensions as the number of square bracket pairs

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
#matrix

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#tensor

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

Scalars and vectors are denoted with lowercase letters while tensors and matrices are denoted using uppercase letters.

Scalar has 0 dimensions
Vector has 1 dimension
Matrix has 2

tensor can be any number of dimensions, 0 dimension tensor is a scalar, 2 is a vector......

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 6]])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

###Creating Random tensors

We use random tensors as neural networks start off with tensors full of random numbers, then they look at the data and update the tensors to better fit the data

In [ ]:
#creating a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3503, 0.8837, 0.3394, 0.8252],
        [0.3827, 0.8710, 0.9756, 0.9651],
        [0.9648, 0.9035, 0.6790, 0.5483]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
#creating a random tensor with a similar shape as an image tensor

#size is an optional named arg just torch.rand(224,224,3) will give the same output
#We use it to make it clearer or when we are passing a variable into tensor.rand
random_tensor_image = torch.rand(size=(224,224,3)) # height, width, colour channels[r,g,b]
random_tensor_image.shape, random_tensor_image.ndim

(torch.Size([224, 224, 3]), 3)

###Zeroes and ones tensors

In [ ]:
#creating a tensor of all zeroes
zeroes = torch.zeros(3,4) #used to make a mask
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeroes * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#creating a tensor of all 1's
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [5]:
range_tensor = torch.arange(0,10)

In [6]:
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
range_tensor.ndim

1

In [9]:
range_tensor.shape

torch.Size([10])

In [12]:
#creating tensors like will give us a new tensor with the same shape as another tensor

ten_zeros = torch.zeros_like(range_tensor)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])