<a href="https://colab.research.google.com/github/ShriVarshaan/pytorch-learning-log/blob/main/pytorch_funamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###00 Pytorch fundamentals

Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
!pip install torch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.6.0+cu124


Creating a scalar tensor

created using torch.tensor



In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim
# the scalar has no dimensions, ndim gives us the numer of dimensions, also called the rank

0

In [ ]:
# getting tensor back as Python int
scalar.item()

7

In [ ]:
#Vectors

vector = torch.tensor([7,7, 8])
vector

tensor([7, 7, 8])

In [ ]:
vector.ndim
#Think of the number of dimensions as the number of square bracket pairs

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
#matrix

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#tensor

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

Scalars and vectors are denoted with lowercase letters while tensors and matrices are denoted using uppercase letters.

Scalar has 0 dimensions
Vector has 1 dimension
Matrix has 2

tensor can be any number of dimensions, 0 dimension tensor is a scalar, 2 is a vector......

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 6]])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

###Creating Random tensors

We use random tensors as neural networks start off with tensors full of random numbers, then they look at the data and update the tensors to better fit the data

In [ ]:
#creating a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3503, 0.8837, 0.3394, 0.8252],
        [0.3827, 0.8710, 0.9756, 0.9651],
        [0.9648, 0.9035, 0.6790, 0.5483]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
#creating a random tensor with a similar shape as an image tensor

#size is an optional named arg just torch.rand(224,224,3) will give the same output
#We use it to make it clearer or when we are passing a variable into tensor.rand
random_tensor_image = torch.rand(size=(224,224,3)) # height, width, colour channels[r,g,b]
random_tensor_image.shape, random_tensor_image.ndim

(torch.Size([224, 224, 3]), 3)

###Zeroes and ones tensors

In [ ]:
#creating a tensor of all zeroes
zeroes = torch.zeros(3,4) #used to make a mask
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeroes * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#creating a tensor of all 1's
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [ ]:
range_tensor = torch.arange(0,10)

In [ ]:
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range_tensor.ndim

1

In [ ]:
range_tensor.shape

torch.Size([10])

In [ ]:
#creating tensors like will give us a new tensor with the same shape as another tensor

ten_zeros = torch.zeros_like(range_tensor)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

default is float32, this will be float32 even if we specify it as None

In [ ]:
float32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=torch.float32, #datatype of the tensor
                              device=None, #the default is CPU
                              requires_grad=False) #whether or not to track gradient
float32_tensor

tensor([3., 6., 9.])

In [ ]:
float32_tensor.type(torch.float16)

tensor([3., 6., 9.], dtype=torch.float16)

Three most commonly encountered issues with tensors are


1) the tensor not being the right datatype
2) tensors not being the right shape
3) tensors not being on the right device


In [ ]:
float32_tensor.dtype

torch.float32

###Getting information from tensors
For shape use tensorName.shape


For datatype use tensorName.dtype


For device use tensorName.device

No brackets as these are tensor attributes

In [ ]:
float32_tensor.shape

torch.Size([3])

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
float32_tensor.device

device(type='cpu')

In [ ]:
float16_tensor = torch.rand(size=(3,5),
                            device=None,
                            dtype=torch.float16)
float16_tensor

tensor([[0.8726, 0.3711, 0.4141, 0.6499, 0.2144],
        [0.6816, 0.3374, 0.6992, 0.1494, 0.3447],
        [0.0044, 0.2739, 0.2100, 0.6694, 0.4829]], dtype=torch.float16)

In [ ]:
float32_tensor

tensor([3., 6., 9.])

In [ ]:
float16_tensor

tensor([[0.8726, 0.3711, 0.4141, 0.6499, 0.2144],
        [0.6816, 0.3374, 0.6992, 0.1494, 0.3447],
        [0.0044, 0.2739, 0.2100, 0.6694, 0.4829]], dtype=torch.float16)

In [ ]:
float16_tensor.ndim

2

In [ ]:
float16_tensor.dtype

torch.float16

In [ ]:
float16_tensor.shape

torch.Size([3, 5])

###Tensor operations

Addition

subtration

multiplication(element-wise)

division

matrix multiplication

In [ ]:
#Addition

tensor = torch.arange(0,3)
tensor

tensor([0, 1, 2])

In [ ]:
tensor + 10

tensor([10, 11, 12])

In [ ]:
tensor * 10

tensor([ 0, 10, 20])

In [ ]:
tensor #Still 0,1,2 as we haven't reassigned our tensor

tensor([0, 1, 2])

In [ ]:
tensor - 10

tensor([-10,  -9,  -8])

In [ ]:
torch.mul(tensor, 10)

tensor([ 0, 10, 20])

In [ ]:
tensor2 = torch.rand(1,3,
                     dtype=torch.float16)
tensor2

tensor([[0.1011, 0.0938, 0.7085]], dtype=torch.float16)

In [ ]:
tensor2 = torch.tensor([[1,2,3]])
tensor = torch.tensor([[[2]]])

In [ ]:
tensor*tensor2

tensor([[[2, 4, 6]]])

In [ ]:
%%time
torch.matmul(tensor,tensor2)

CPU times: user 845 µs, sys: 0 ns, total: 845 µs
Wall time: 521 µs


tensor([[[2, 4, 6]]])

In [ ]:
tensor.shape

torch.Size([1, 1, 1])

In [17]:
tensorA = torch.tensor([[1,2],
                       [3,4],
                       [5,6]],)
tensorB = torch.tensor([[7,10,12],
                       [8,11,13],])

tensorC = torch.tensor(5)
tensorC.dtype

torch.int64

torch.float32

In [5]:
#Transpose

tensorA @ tensorA.T

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [14]:
tensorA.dtype

torch.float64

###Tensor aggregation

In [24]:
torch.min(tensorA) #can use tensor.min or you can use tensorName.min

tensor(1)

In [8]:
tensorA.max()

tensor(6)

In [9]:
tensorA.min()

tensor(1)

The tensorNAme.mean() requires a float datatype not int

In [23]:
tensorA.type(torch.float32).mean()

tensor(3.5000)

In [11]:
tensorA.dtype

torch.int64